name: Database
abbreviation: db
checker: PragmaRX\Health\Checkers\Database
notify: true
column_size: 3
targets:
  - users:
      type: "find_first_model"
      models:
        - "{{ config('auth.providers.users.model') }}"
