name: Bộ nhớ còn trống
abbreviation: 4
checker: PragmaRX\Health\Checkers\DiskSpace
notify: true
column_size: 3
targets:
  - default:
      name: root
      path: "/"
      minimum: 1GB
      message:
        "Volume %s is getting out of space. It has %s when it should have at least %s."
